// Code generated by goctl. DO NOT EDIT.
// Source: school.proto

package server

import (
	"context"

	"github.com/xxcheng123/primary-school-system/rpc/internal/logic/user"
	"github.com/xxcheng123/primary-school-system/rpc/internal/svc"
	"github.com/xxcheng123/primary-school-system/rpc/pb"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) CreateUser(ctx context.Context, in *pb.CreateUserReq) (*pb.CreateUserResp, error) {
	l := userlogic.NewCreateUserLogic(ctx, s.svcCtx)
	return l.CreateUser(in)
}

func (s *UserServer) LoginUser(ctx context.Context, in *pb.LoginUserReq) (*pb.InfoUserResp, error) {
	l := userlogic.NewLoginUserLogic(ctx, s.svcCtx)
	return l.LoginUser(in)
}

func (s *UserServer) GetInfoUser(ctx context.Context, in *pb.GetInfoUserReq) (*pb.InfoUserResp, error) {
	l := userlogic.NewGetInfoUserLogic(ctx, s.svcCtx)
	return l.GetInfoUser(in)
}
