// Code generated by goctl. DO NOT EDIT.
// Source: school.proto

package server

import (
	"context"

	"github.com/xxcheng123/primary-school-system/rpc/internal/logic/article"
	"github.com/xxcheng123/primary-school-system/rpc/internal/svc"
	"github.com/xxcheng123/primary-school-system/rpc/pb"
)

type ArticleServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedArticleServer
}

func NewArticleServer(svcCtx *svc.ServiceContext) *ArticleServer {
	return &ArticleServer{
		svcCtx: svcCtx,
	}
}

func (s *ArticleServer) CreateArticle(ctx context.Context, in *pb.CreateArticleReq) (*pb.CreateArticleResp, error) {
	l := articlelogic.NewCreateArticleLogic(ctx, s.svcCtx)
	return l.CreateArticle(in)
}

func (s *ArticleServer) GetArticle(ctx context.Context, in *pb.GetInfoArticleReq) (*pb.ArticleInfo, error) {
	l := articlelogic.NewGetArticleLogic(ctx, s.svcCtx)
	return l.GetArticle(in)
}

func (s *ArticleServer) GetListArticle(ctx context.Context, in *pb.GetListArticleReq) (*pb.GetListArticleResp, error) {
	l := articlelogic.NewGetListArticleLogic(ctx, s.svcCtx)
	return l.GetListArticle(in)
}
