// Code generated by goctl. DO NOT EDIT.
// Source: school.proto

package server

import (
	"context"

	"github.com/xxcheng123/primary-school-system/rpc/internal/logic/base"
	"github.com/xxcheng123/primary-school-system/rpc/internal/svc"
	"github.com/xxcheng123/primary-school-system/rpc/pb"
)

type BaseServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedBaseServer
}

func NewBaseServer(svcCtx *svc.ServiceContext) *BaseServer {
	return &BaseServer{
		svcCtx: svcCtx,
	}
}

func (s *BaseServer) Ping(ctx context.Context, in *pb.Request) (*pb.Response, error) {
	l := baselogic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
