// Code generated by goctl. DO NOT EDIT.
// Source: school.proto

package server

import (
	"context"

	"github.com/xxcheng123/primary-school-system/rpc/internal/logic/category"
	"github.com/xxcheng123/primary-school-system/rpc/internal/svc"
	"github.com/xxcheng123/primary-school-system/rpc/pb"
)

type CategoryServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedCategoryServer
}

func NewCategoryServer(svcCtx *svc.ServiceContext) *CategoryServer {
	return &CategoryServer{
		svcCtx: svcCtx,
	}
}

func (s *CategoryServer) CreateCategory(ctx context.Context, in *pb.CreateCategoryReq) (*pb.CategoryInfo, error) {
	l := categorylogic.NewCreateCategoryLogic(ctx, s.svcCtx)
	return l.CreateCategory(in)
}

func (s *CategoryServer) GetCategory(ctx context.Context, in *pb.GetCategoryReq) (*pb.CategoryInfo, error) {
	l := categorylogic.NewGetCategoryLogic(ctx, s.svcCtx)
	return l.GetCategory(in)
}

func (s *CategoryServer) GetListCategory(ctx context.Context, in *pb.GetListCategoryReq) (*pb.ListCategoryResp, error) {
	l := categorylogic.NewGetListCategoryLogic(ctx, s.svcCtx)
	return l.GetListCategory(in)
}
