// Code generated by goctl. DO NOT EDIT.
// Source: school.proto

package user

import (
	"context"

	"github.com/xxcheng123/primary-school-system/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddSwiperReq       = pb.AddSwiperReq
	ArticleInfo        = pb.ArticleInfo
	CategoryInfo       = pb.CategoryInfo
	CreateArticleReq   = pb.CreateArticleReq
	CreateArticleResp  = pb.CreateArticleResp
	CreateCategoryReq  = pb.CreateCategoryReq
	CreateUserReq      = pb.CreateUserReq
	CreateUserResp     = pb.CreateUserResp
	GetCategoryReq     = pb.GetCategoryReq
	GetInfoArticleReq  = pb.GetInfoArticleReq
	GetInfoUserReq     = pb.GetInfoUserReq
	GetListArticleReq  = pb.GetListArticleReq
	GetListArticleResp = pb.GetListArticleResp
	GetListCategoryReq = pb.GetListCategoryReq
	InfoSwiper         = pb.InfoSwiper
	InfoUserResp       = pb.InfoUserResp
	ListCategoryResp   = pb.ListCategoryResp
	ListSwiperReq      = pb.ListSwiperReq
	ListSwiperResp     = pb.ListSwiperResp
	LoginUserReq       = pb.LoginUserReq
	OperateSwiperReq   = pb.OperateSwiperReq
	OperateSwiperResp  = pb.OperateSwiperResp
	Request            = pb.Request
	Response           = pb.Response
	UpdateSwiperReq    = pb.UpdateSwiperReq
	UserInfo           = pb.UserInfo

	User interface {
		CreateUser(ctx context.Context, in *CreateUserReq, opts ...grpc.CallOption) (*CreateUserResp, error)
		LoginUser(ctx context.Context, in *LoginUserReq, opts ...grpc.CallOption) (*InfoUserResp, error)
		GetInfoUser(ctx context.Context, in *GetInfoUserReq, opts ...grpc.CallOption) (*InfoUserResp, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) CreateUser(ctx context.Context, in *CreateUserReq, opts ...grpc.CallOption) (*CreateUserResp, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.CreateUser(ctx, in, opts...)
}

func (m *defaultUser) LoginUser(ctx context.Context, in *LoginUserReq, opts ...grpc.CallOption) (*InfoUserResp, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.LoginUser(ctx, in, opts...)
}

func (m *defaultUser) GetInfoUser(ctx context.Context, in *GetInfoUserReq, opts ...grpc.CallOption) (*InfoUserResp, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.GetInfoUser(ctx, in, opts...)
}
