// Code generated by goctl. DO NOT EDIT.
// Source: school.proto

package article

import (
	"context"

	"github.com/xxcheng123/primary-school-system/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddSwiperReq       = pb.AddSwiperReq
	ArticleInfo        = pb.ArticleInfo
	CategoryInfo       = pb.CategoryInfo
	CreateArticleReq   = pb.CreateArticleReq
	CreateArticleResp  = pb.CreateArticleResp
	CreateCategoryReq  = pb.CreateCategoryReq
	CreateUserReq      = pb.CreateUserReq
	CreateUserResp     = pb.CreateUserResp
	GetCategoryReq     = pb.GetCategoryReq
	GetInfoArticleReq  = pb.GetInfoArticleReq
	GetInfoUserReq     = pb.GetInfoUserReq
	GetListArticleReq  = pb.GetListArticleReq
	GetListArticleResp = pb.GetListArticleResp
	GetListCategoryReq = pb.GetListCategoryReq
	InfoSwiper         = pb.InfoSwiper
	InfoUserResp       = pb.InfoUserResp
	ListCategoryResp   = pb.ListCategoryResp
	ListSwiperReq      = pb.ListSwiperReq
	ListSwiperResp     = pb.ListSwiperResp
	LoginUserReq       = pb.LoginUserReq
	OperateSwiperReq   = pb.OperateSwiperReq
	OperateSwiperResp  = pb.OperateSwiperResp
	Request            = pb.Request
	Response           = pb.Response
	UpdateSwiperReq    = pb.UpdateSwiperReq
	UserInfo           = pb.UserInfo

	Article interface {
		CreateArticle(ctx context.Context, in *CreateArticleReq, opts ...grpc.CallOption) (*CreateArticleResp, error)
		GetArticle(ctx context.Context, in *GetInfoArticleReq, opts ...grpc.CallOption) (*ArticleInfo, error)
		GetListArticle(ctx context.Context, in *GetListArticleReq, opts ...grpc.CallOption) (*GetListArticleResp, error)
	}

	defaultArticle struct {
		cli zrpc.Client
	}
)

func NewArticle(cli zrpc.Client) Article {
	return &defaultArticle{
		cli: cli,
	}
}

func (m *defaultArticle) CreateArticle(ctx context.Context, in *CreateArticleReq, opts ...grpc.CallOption) (*CreateArticleResp, error) {
	client := pb.NewArticleClient(m.cli.Conn())
	return client.CreateArticle(ctx, in, opts...)
}

func (m *defaultArticle) GetArticle(ctx context.Context, in *GetInfoArticleReq, opts ...grpc.CallOption) (*ArticleInfo, error) {
	client := pb.NewArticleClient(m.cli.Conn())
	return client.GetArticle(ctx, in, opts...)
}

func (m *defaultArticle) GetListArticle(ctx context.Context, in *GetListArticleReq, opts ...grpc.CallOption) (*GetListArticleResp, error) {
	client := pb.NewArticleClient(m.cli.Conn())
	return client.GetListArticle(ctx, in, opts...)
}
